---
- name: Add bitnami chart repo
  community.kubernetes.helm_repository:
    state: present
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Deploy mongodb
  community.kubernetes.helm:
    state: "{{ mongodb_state }}"
    name: mongodb
    namespace: "{{ mongodb_namespace }}"
    create_namespace: true
    chart_ref: bitnami/mongodb
    chart_version: 12.1.20
    # 若values文件中有 "{{ xxx }}" 的值，可以采用 "[% xxx %]" 的方式，如下
    # values: "{{ lookup('template', 'mongodb_values.yml.j2', variable_start_string='[%', variable_end_string='%]') | from_yaml | combine(mongodb_chart_values, recursive=True) }}"
    values: "{{ lookup('template', 'mongodb_values.yml.j2') | from_yaml | combine(mongodb_chart_values, recursive=True) }}"
    wait: "{{ wait }}"
    wait_timeout: 10m
  register: mongodb_installed
